//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.17.0
//     from Assets/Input/VRMenuInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/VRMenuInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @VRMenuInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @VRMenuInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""VRMenuInputActions"",
    ""maps"": [
        {
            ""name"": ""VR Menu"",
            ""id"": ""a1b2c3d4-e5f6-7890-abcd-ef1234567890"",
            ""actions"": [
                {
                    ""name"": ""Toggle Menu"",
                    ""type"": ""Button"",
                    ""id"": ""12345678-90ab-cdef-1234-567890abcdef"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab Left"",
                    ""type"": ""Button"",
                    ""id"": ""22222222-3333-4444-5555-666666666666"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab Right"",
                    ""type"": ""Button"",
                    ""id"": ""aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use"",
                    ""type"": ""Button"",
                    ""id"": ""33333333-4444-5555-6666-777777777777"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Primary Button Left"",
                    ""type"": ""Button"",
                    ""id"": ""11111111-aaaa-bbbb-cccc-111111111111"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Primary Button Right"",
                    ""type"": ""Button"",
                    ""id"": ""22222222-aaaa-bbbb-cccc-222222222222"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Secondary Button Left"",
                    ""type"": ""Button"",
                    ""id"": ""33333333-aaaa-bbbb-cccc-333333333333"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Secondary Button Right"",
                    ""type"": ""Button"",
                    ""id"": ""44444444-aaaa-bbbb-cccc-444444444444"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Trigger Left"",
                    ""type"": ""Button"",
                    ""id"": ""55555555-aaaa-bbbb-cccc-555555555555"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Trigger Right"",
                    ""type"": ""Button"",
                    ""id"": ""66666666-aaaa-bbbb-cccc-666666666666"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Thumbstick Press Left"",
                    ""type"": ""Button"",
                    ""id"": ""77777777-aaaa-bbbb-cccc-777777777777"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Thumbstick Press Right"",
                    ""type"": ""Button"",
                    ""id"": ""88888888-aaaa-bbbb-cccc-888888888888"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""abcdef12-3456-7890-abcd-ef1234567890"",
                    ""path"": ""<XRController>{RightHand}/menuButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Toggle Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fedcba09-8765-4321-fedc-ba0987654321"",
                    ""path"": ""<XRController>{LeftHand}/menuButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Toggle Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55555555-6666-7777-8888-999999999999"",
                    ""path"": ""<XRController>{LeftHand}/gripButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Grab Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99999999-aaaa-bbbb-cccc-dddddddddddd"",
                    ""path"": ""<XRSimulatedController>{LeftHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Grab Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44444444-5555-6666-7777-888888888888"",
                    ""path"": ""<XRController>{RightHand}/gripButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Grab Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88888888-9999-aaaa-bbbb-cccccccccccc"",
                    ""path"": ""<XRSimulatedController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Grab Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66666666-7777-8888-9999-aaaaaaaaaaaa"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77777777-8888-9999-aaaa-bbbbbbbbbbbb"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aaaaaaaa-1111-2222-3333-111111111111"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Primary Button Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbbbbbbb-1111-2222-3333-222222222222"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Primary Button Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cccccccc-1111-2222-3333-333333333333"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Secondary Button Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dddddddd-1111-2222-3333-444444444444"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Secondary Button Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eeeeeeee-1111-2222-3333-555555555555"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Trigger Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffffffff-1111-2222-3333-666666666666"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Trigger Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11111111-2222-3333-4444-777777777777"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Thumbstick Press Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22222222-2222-3333-4444-888888888888"",
                    ""path"": ""<XRController>{RightHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Thumbstick Press Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // VR Menu
        m_VRMenu = asset.FindActionMap("VR Menu", throwIfNotFound: true);
        m_VRMenu_ToggleMenu = m_VRMenu.FindAction("Toggle Menu", throwIfNotFound: true);
        m_VRMenu_GrabLeft = m_VRMenu.FindAction("Grab Left", throwIfNotFound: true);
        m_VRMenu_GrabRight = m_VRMenu.FindAction("Grab Right", throwIfNotFound: true);
        m_VRMenu_Use = m_VRMenu.FindAction("Use", throwIfNotFound: true);
        m_VRMenu_PrimaryButtonLeft = m_VRMenu.FindAction("Primary Button Left", throwIfNotFound: true);
        m_VRMenu_PrimaryButtonRight = m_VRMenu.FindAction("Primary Button Right", throwIfNotFound: true);
        m_VRMenu_SecondaryButtonLeft = m_VRMenu.FindAction("Secondary Button Left", throwIfNotFound: true);
        m_VRMenu_SecondaryButtonRight = m_VRMenu.FindAction("Secondary Button Right", throwIfNotFound: true);
        m_VRMenu_TriggerLeft = m_VRMenu.FindAction("Trigger Left", throwIfNotFound: true);
        m_VRMenu_TriggerRight = m_VRMenu.FindAction("Trigger Right", throwIfNotFound: true);
        m_VRMenu_ThumbstickPressLeft = m_VRMenu.FindAction("Thumbstick Press Left", throwIfNotFound: true);
        m_VRMenu_ThumbstickPressRight = m_VRMenu.FindAction("Thumbstick Press Right", throwIfNotFound: true);
    }

    ~@VRMenuInputActions()
    {
        UnityEngine.Debug.Assert(!m_VRMenu.enabled, "This will cause a leak and performance issues, VRMenuInputActions.VRMenu.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VR Menu
    private readonly InputActionMap m_VRMenu;
    private List<IVRMenuActions> m_VRMenuActionsCallbackInterfaces = new List<IVRMenuActions>();
    private readonly InputAction m_VRMenu_ToggleMenu;
    private readonly InputAction m_VRMenu_GrabLeft;
    private readonly InputAction m_VRMenu_GrabRight;
    private readonly InputAction m_VRMenu_Use;
    private readonly InputAction m_VRMenu_PrimaryButtonLeft;
    private readonly InputAction m_VRMenu_PrimaryButtonRight;
    private readonly InputAction m_VRMenu_SecondaryButtonLeft;
    private readonly InputAction m_VRMenu_SecondaryButtonRight;
    private readonly InputAction m_VRMenu_TriggerLeft;
    private readonly InputAction m_VRMenu_TriggerRight;
    private readonly InputAction m_VRMenu_ThumbstickPressLeft;
    private readonly InputAction m_VRMenu_ThumbstickPressRight;
    /// <summary>
    /// Provides access to input actions defined in input action map "VR Menu".
    /// </summary>
    public struct VRMenuActions
    {
        private @VRMenuInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public VRMenuActions(@VRMenuInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/ToggleMenu".
        /// </summary>
        public InputAction @ToggleMenu => m_Wrapper.m_VRMenu_ToggleMenu;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/GrabLeft".
        /// </summary>
        public InputAction @GrabLeft => m_Wrapper.m_VRMenu_GrabLeft;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/GrabRight".
        /// </summary>
        public InputAction @GrabRight => m_Wrapper.m_VRMenu_GrabRight;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/Use".
        /// </summary>
        public InputAction @Use => m_Wrapper.m_VRMenu_Use;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/PrimaryButtonLeft".
        /// </summary>
        public InputAction @PrimaryButtonLeft => m_Wrapper.m_VRMenu_PrimaryButtonLeft;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/PrimaryButtonRight".
        /// </summary>
        public InputAction @PrimaryButtonRight => m_Wrapper.m_VRMenu_PrimaryButtonRight;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/SecondaryButtonLeft".
        /// </summary>
        public InputAction @SecondaryButtonLeft => m_Wrapper.m_VRMenu_SecondaryButtonLeft;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/SecondaryButtonRight".
        /// </summary>
        public InputAction @SecondaryButtonRight => m_Wrapper.m_VRMenu_SecondaryButtonRight;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/TriggerLeft".
        /// </summary>
        public InputAction @TriggerLeft => m_Wrapper.m_VRMenu_TriggerLeft;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/TriggerRight".
        /// </summary>
        public InputAction @TriggerRight => m_Wrapper.m_VRMenu_TriggerRight;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/ThumbstickPressLeft".
        /// </summary>
        public InputAction @ThumbstickPressLeft => m_Wrapper.m_VRMenu_ThumbstickPressLeft;
        /// <summary>
        /// Provides access to the underlying input action "VRMenu/ThumbstickPressRight".
        /// </summary>
        public InputAction @ThumbstickPressRight => m_Wrapper.m_VRMenu_ThumbstickPressRight;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_VRMenu; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="VRMenuActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(VRMenuActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="VRMenuActions" />
        public void AddCallbacks(IVRMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_VRMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VRMenuActionsCallbackInterfaces.Add(instance);
            @ToggleMenu.started += instance.OnToggleMenu;
            @ToggleMenu.performed += instance.OnToggleMenu;
            @ToggleMenu.canceled += instance.OnToggleMenu;
            @GrabLeft.started += instance.OnGrabLeft;
            @GrabLeft.performed += instance.OnGrabLeft;
            @GrabLeft.canceled += instance.OnGrabLeft;
            @GrabRight.started += instance.OnGrabRight;
            @GrabRight.performed += instance.OnGrabRight;
            @GrabRight.canceled += instance.OnGrabRight;
            @Use.started += instance.OnUse;
            @Use.performed += instance.OnUse;
            @Use.canceled += instance.OnUse;
            @PrimaryButtonLeft.started += instance.OnPrimaryButtonLeft;
            @PrimaryButtonLeft.performed += instance.OnPrimaryButtonLeft;
            @PrimaryButtonLeft.canceled += instance.OnPrimaryButtonLeft;
            @PrimaryButtonRight.started += instance.OnPrimaryButtonRight;
            @PrimaryButtonRight.performed += instance.OnPrimaryButtonRight;
            @PrimaryButtonRight.canceled += instance.OnPrimaryButtonRight;
            @SecondaryButtonLeft.started += instance.OnSecondaryButtonLeft;
            @SecondaryButtonLeft.performed += instance.OnSecondaryButtonLeft;
            @SecondaryButtonLeft.canceled += instance.OnSecondaryButtonLeft;
            @SecondaryButtonRight.started += instance.OnSecondaryButtonRight;
            @SecondaryButtonRight.performed += instance.OnSecondaryButtonRight;
            @SecondaryButtonRight.canceled += instance.OnSecondaryButtonRight;
            @TriggerLeft.started += instance.OnTriggerLeft;
            @TriggerLeft.performed += instance.OnTriggerLeft;
            @TriggerLeft.canceled += instance.OnTriggerLeft;
            @TriggerRight.started += instance.OnTriggerRight;
            @TriggerRight.performed += instance.OnTriggerRight;
            @TriggerRight.canceled += instance.OnTriggerRight;
            @ThumbstickPressLeft.started += instance.OnThumbstickPressLeft;
            @ThumbstickPressLeft.performed += instance.OnThumbstickPressLeft;
            @ThumbstickPressLeft.canceled += instance.OnThumbstickPressLeft;
            @ThumbstickPressRight.started += instance.OnThumbstickPressRight;
            @ThumbstickPressRight.performed += instance.OnThumbstickPressRight;
            @ThumbstickPressRight.canceled += instance.OnThumbstickPressRight;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="VRMenuActions" />
        private void UnregisterCallbacks(IVRMenuActions instance)
        {
            @ToggleMenu.started -= instance.OnToggleMenu;
            @ToggleMenu.performed -= instance.OnToggleMenu;
            @ToggleMenu.canceled -= instance.OnToggleMenu;
            @GrabLeft.started -= instance.OnGrabLeft;
            @GrabLeft.performed -= instance.OnGrabLeft;
            @GrabLeft.canceled -= instance.OnGrabLeft;
            @GrabRight.started -= instance.OnGrabRight;
            @GrabRight.performed -= instance.OnGrabRight;
            @GrabRight.canceled -= instance.OnGrabRight;
            @Use.started -= instance.OnUse;
            @Use.performed -= instance.OnUse;
            @Use.canceled -= instance.OnUse;
            @PrimaryButtonLeft.started -= instance.OnPrimaryButtonLeft;
            @PrimaryButtonLeft.performed -= instance.OnPrimaryButtonLeft;
            @PrimaryButtonLeft.canceled -= instance.OnPrimaryButtonLeft;
            @PrimaryButtonRight.started -= instance.OnPrimaryButtonRight;
            @PrimaryButtonRight.performed -= instance.OnPrimaryButtonRight;
            @PrimaryButtonRight.canceled -= instance.OnPrimaryButtonRight;
            @SecondaryButtonLeft.started -= instance.OnSecondaryButtonLeft;
            @SecondaryButtonLeft.performed -= instance.OnSecondaryButtonLeft;
            @SecondaryButtonLeft.canceled -= instance.OnSecondaryButtonLeft;
            @SecondaryButtonRight.started -= instance.OnSecondaryButtonRight;
            @SecondaryButtonRight.performed -= instance.OnSecondaryButtonRight;
            @SecondaryButtonRight.canceled -= instance.OnSecondaryButtonRight;
            @TriggerLeft.started -= instance.OnTriggerLeft;
            @TriggerLeft.performed -= instance.OnTriggerLeft;
            @TriggerLeft.canceled -= instance.OnTriggerLeft;
            @TriggerRight.started -= instance.OnTriggerRight;
            @TriggerRight.performed -= instance.OnTriggerRight;
            @TriggerRight.canceled -= instance.OnTriggerRight;
            @ThumbstickPressLeft.started -= instance.OnThumbstickPressLeft;
            @ThumbstickPressLeft.performed -= instance.OnThumbstickPressLeft;
            @ThumbstickPressLeft.canceled -= instance.OnThumbstickPressLeft;
            @ThumbstickPressRight.started -= instance.OnThumbstickPressRight;
            @ThumbstickPressRight.performed -= instance.OnThumbstickPressRight;
            @ThumbstickPressRight.canceled -= instance.OnThumbstickPressRight;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="VRMenuActions.UnregisterCallbacks(IVRMenuActions)" />.
        /// </summary>
        /// <seealso cref="VRMenuActions.UnregisterCallbacks(IVRMenuActions)" />
        public void RemoveCallbacks(IVRMenuActions instance)
        {
            if (m_Wrapper.m_VRMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="VRMenuActions.AddCallbacks(IVRMenuActions)" />
        /// <seealso cref="VRMenuActions.RemoveCallbacks(IVRMenuActions)" />
        /// <seealso cref="VRMenuActions.UnregisterCallbacks(IVRMenuActions)" />
        public void SetCallbacks(IVRMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_VRMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VRMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="VRMenuActions" /> instance referencing this action map.
    /// </summary>
    public VRMenuActions @VRMenu => new VRMenuActions(this);
    private int m_XRSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "VR Menu" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="VRMenuActions.AddCallbacks(IVRMenuActions)" />
    /// <seealso cref="VRMenuActions.RemoveCallbacks(IVRMenuActions)" />
    public interface IVRMenuActions
    {
        /// <summary>
        /// Method invoked when associated input action "Toggle Menu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleMenu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Grab Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGrabLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Grab Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGrabRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Use" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUse(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Primary Button Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimaryButtonLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Primary Button Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimaryButtonRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Secondary Button Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSecondaryButtonLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Secondary Button Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSecondaryButtonRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Trigger Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Trigger Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Thumbstick Press Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThumbstickPressLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Thumbstick Press Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThumbstickPressRight(InputAction.CallbackContext context);
    }
}
